### ISSUE TITLE
Remove console.log calls

### ISSUE THREAD

**Issue by GrahamGoudeau** [GrahamGoudeau/tsIgetback#49]
Running `grep -rnIi console api/**.ts spec/**.ts utils/**.ts *.ts` in the `server/` directory shows many direct calls to `console.log`. Remove all of the ones not in the logger or in the `spec/` directory.

**Comment by joshleetufts** [comment]
Issue Resolved

**Comment by GrahamGoudeau** [comment]
Waiting for pull request

**Comment by tekknolagi** [comment]
@joshleetufts any progress on this?

**Comment by GrahamGoudeau** [comment]
This is merged
